language: node_js
node_js:
- 0.1
deploy:
  provider: npm
  email: adriaan.callaerts@gmail.com
  api_key:
    secure: vXWaLlu20bmjRRDitksWFmtxHmpI2JeqCjLZPnjkE1oR7jiUwMzq9o97MrjUpMnD6/qZD+frtyNFMVsXivQ79y03y2EqAQH5X9y+wagOCB9SAkHWo5Be9XiZc3ksBGqBD7uODSTCpMk4WPlVVsUjGOmJxf52NURMHB8TOugLRVs=
  on:
    tags: true
    repo: call-a3/gulp-loader
